# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4a54122df8c381c1b5b9aedd6327c0a5329b0918d2950bba8a1c24548539d8d9a1914906de6cd45e59fe056c7bcf9fc5e9b47b5ed55e73cfadbdea9b1b1da20d

test:
  secret_key_base: d883e01e4934c9e4a527241a0e8d017cfb720366028dc50abd841bb4d3cb294d02e7d90088592311c56eee425abaa3df446d059e51191828d143aaab15f83b15

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
